steps:
- # Build ${_APP_NAME} image
  id: build
  name: gcr.io/cloud-builders/docker:latest
  args: ['build','-t', 'gcr.io/${_PROJECT_ID}/${_APP_NAME}:${_TAG}', '-f', 'Dockerfile', '.']
  dir: '${_DIR}'

- # Push the container image to Artifact Registry
  id: push
  name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_APP_NAME}:${_TAG}']
  waitFor: ['build']

- # Deploy to Cloud Run
  # name: google/cloud-sdk
  id: run
  name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', '${_APP_NAME}', 
         '--image', 'gcr.io/${_PROJECT_ID}/${_APP_NAME}:${_TAG}',
         '--region', '${_REGION}',
         '--platform', 'managed',
         '--allow-unauthenticated',
         '--port', '8080',
  ] 
  waitFor: ['push'] 

  
# - # Update traffic
#   id: update
#   name: gcr.io/cloud-builders/gcloud
#   args: ['run', 'services', 'update-traffic', '${_APP_NAME}', '--to-latest', '--region', '${_REGION}'
#   ]
#   waitFor: ['run']

options:
  logging: CLOUD_LOGGING_ONLY 

# images: [
#   'gcr.io/${_PROJECT_ID}/${_APP_NAME}:${_TAG}'
# ]

substitutions:
  _TAG: latest 
  _PROJECT_ID: weaceace
  _APP_NAME: go-app
  _REGION: europe-west1
  _DIR: golang/go-cloud-run-hello-world
